version: "3.1"
services:
    www:
        image: diorcokorea/dentone
        container_name: dentone
        build: .
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - mariadb
        networks:
            - dentnet
    mariadb:
        image: mariadb:10.6
        container_name: mariadb
        ports:
            - "40000:3306"
        command: --lower_case_table_names=1
        environment:
            MYSQL_DATABASE: aligner
            MYSQL_USER: root
            MYSQL_PASSWORD: 9080
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - maria-data:/var/lib/mysql
        networks:
            - dentnet
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     links: 
    #         - db:db
    #     ports:
    #         - 8000:80
    #     environment:
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: test
    #         MYSQL_ROOT_PASSWORD: test 
volumes:
    maria-data:
        name: maria-data
networks:
    dentnet:
        driver: bridge
        name: dentnet
